name: Rust

on:
  push:
    paths:
      - '.github/workflows/rust.yml'
      - 'rust/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/rust.yml'
      - 'rust/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: i686-pc-windows-gnu, i686-pc-windows-msvc, x86_64-pc-windows-gnu, x86_64-pc-windows-msvc
      - name: Format
        run: cargo fmt --all --check
      - name: Lint
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace --all-targets
      - name: Build C static libraries
        run: |
          cargo build --release --package rufus-ffi --target i686-pc-windows-gnu
          cargo build --release --package rufus-ffi --target i686-pc-windows-msvc
          cargo build --release --package rufus-ffi --target x86_64-pc-windows-gnu
          cargo build --release --package rufus-ffi --target x86_64-pc-windows-msvc

  msrv:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@1.85.0
      - name: Test MSRV
        run: cargo test --workspace --all-targets
